=== sam18111999/webstack/XML/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="company">
	<xs:complexType>
	    <xs:sequence>
	        <xs:element name="employee" maxOccurs="unbounded">
	        	<xs:complexType>
                                    <xs:attribute name="ID" type="xs:string" />
				    <xs:sequence>
                                                 <xs:element name="ID"  type="xs:string"/>
                                                 <xs:unique name="EmployeeIDKey">
                                                    <xs:selector xpath="./employee" />
                                                    <xs:field xpath="@ID" />
                                                 </xs:unique>
                                                <xs:element name="name"  type="xs:string"/>
						<xs:element name="age"  type="xs:integer"/>
				                <xs:element name="salary" minOccurs="50000" maxOccurs="200000" type="xs:integer"/>
				                <xs:element name="email"  type="xs:string"/>
				                <xs:element name="phone"  type="xs:integer"/>
            			                <xs:element name="designation"  type="xs:string"/>
                                                <xs:element name="promotion"  type="xs:string"/>
				    </xs:sequence>
				</xs:complexType>
	        </xs:element>
	    </xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== sam18111999/webstack/XML/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="company.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="company.xsd"> 
	
	<employee>
                <name>Samarth</name>
		<age>22</age>
		<salary>80,000/-</salary>
		<email>sam99@gmail.com</email>
		<phone>+91 1234567891</phone>
		<designation>sales manager</designation>
                <promotion>               </promotion>
        </employee>
        <employee>
                <name>Emmanuel</name>
		<age>23</age>
		<salary>50,000/-</salary>
		<email>emmanuel123@gmail.com</email>
		<phone>+91 1234567891</phone>
		<designation>IT manager</designation>
                <promotion>               </promotion>
        </employee>
        <employee>
                <name>Rakshith R</name>
		<age>25</age>
		<salary>1,00,000/-</salary>
		<email>rakshith123@gmail.com</email>
		<phone>+91 1234567891</phone>
		<designation>ux team lead</designation>
                <promotion>               </promotion>
        </employee>
         <employee>
                <name>Sourav G</name>
		<age>24</age>
		<salary>2,00,000/-</salary>
		<email>sourav123@gmail.com</email>
		<phone>+91 1234567891</phone>
		<designation>vice president</designation>
                <promotion>               </promotion>
        </employee>
       
	
</company>
