=== sam18111999/webstack/XML/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Emp-id" type="xs:integer"/>
                            <xs:element name="Emp-name" type="xs:string"/>
                            <xs:element name="Emp-age" type="xs:integer"/>
                            <xs:element name="Emp-salary" type="xs:integer"/>
                            <xs:element name="Emp-email" type="xs:string"/>
                            <xs:element name="Emp-phone" type="xs:string"/>
                            <xs:element name="Emp-designation" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sam18111999/webstack/XML/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Employee.xsd">

    <employee>
        <Emp-id>101</Emp-id>
        <Emp-name> Samarth</Emp-name>
        <Emp-age>21</Emp-age>
        <Emp-salary>25000</Emp-salary>
        <Emp-email>samarth@gmail.com</Emp-email>
        <Emp-phone>9108413067</Emp-phone>
        <Emp-designation>Manager</Emp-designation>
    </employee>
    <employee>
        <Emp-id>102</Emp-id>
        <Emp-name> Rakesh</Emp-name>
        <Emp-age>55</Emp-age>
        <Emp-salary>50000</Emp-salary>
        <Emp-email>rakesh@gmail.com</Emp-email>
        <Emp-phone>9108413477</Emp-phone>
        <Emp-designation>General Manager</Emp-designation>
    </employee>
    <employee>
        <Emp-id>103</Emp-id>
        <Emp-name> Emmanuel</Emp-name>
        <Emp-age>45</Emp-age>
        <Emp-salary>45000</Emp-salary>
        <Emp-email>emmanuel@gmail.com</Emp-email>
        <Emp-phone>9107533067</Emp-phone>
        <Emp-designation>Developer</Emp-designation>
    </employee>



</company>
